# Generated by Django 4.0.6 on 2022-07-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('sexo', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
